[functions."schedule-notification"]
schedule = "* * * * *"

[build]
  command = "cd netlify/functions && npm install && cd ../../ && npm install"

[[headers]]
  for = "/firebase-messaging-sw.js"
  [headers.values]
    Service-Worker-Allowed = "/"
    Cache-Control = "no-cache"